forms.py
from flask_wtf import FlaskForm
from wtforms import Form, StringField, RadioField, SelectField, TextAreaField, EmailField, SubmitField, validators


class createEnquiryForm(Form):
    name = StringField('Name', [validators.length(3, 128, message='Name must be between 3 to 128 characters'),
                                validators.DataRequired(message='Name is required')])
    email = EmailField('Email', [validators.Email(granular_message=True),
                                 validators.DataRequired(message='Email is required')])
    purpose = SelectField('Purpose', [validators.DataRequired('Purpose is required')],
                          choices=[("", 'Select a Purpose'), ('General Questions', 'General Questions'),
                                   ('Feedback / Feature Request', 'Feedback / Feature Request')], default=""
                          )
    query = TextAreaField('Enquiry',
                          [validators.length(3, 1000, message='Enquiry must be between 3 to 1000 characters'),
                           validators.DataRequired('Enquiry is required')])
    submit = SubmitField('Submit')

app.py
from flask import Flask, render_template

from routes.central import central
from routes.east import east
from routes.enquiry import enquiry
from routes.north import north
from routes.south import south
from routes.west import west

app = Flask(__name__)
app.secret_key = 'RTYUjnbgf59ij34rhgieudfk'

app.register_blueprint(enquiry)
app.register_blueprint(south)
app.register_blueprint(west)
app.register_blueprint(north)
app.register_blueprint(east)
app.register_blueprint(central)


@app.route('/')
def home():
    return render_template('home.html')


if __name__ == '__main__':
    app.run(debug=True)

routes/central.py
import shelve

from flask import Blueprint, render_template
from flask import flash, render_template, redirect, url_for, request

from classes.Enquiry import Enquiry
from forms import createEnquiryForm

central = Blueprint('central', __name__)

@central.route('/central')
def viewCentral():
    return render_template("central/central.html")

@central.route('/central/DragonPlayground')
def viewDragonPlayground():
    return render_template("central/Dragon_Playground.html")


@central.route('/central/NationalOrchidGarden')
def viewNationalOrchidGarden():
    return render_template("central/National_Orchid_Garden.html")

routes/east.py
import shelve

from flask import Blueprint, render_template
from flask import flash, render_template, redirect, url_for, request

from classes.Enquiry import Enquiry
from forms import createEnquiryForm

east = Blueprint('east', __name__)

@east.route('/east')
def viewEast():
    return render_template("east/east.html")

@east.route('/east/ChangiBayPoint')
def viewLazarusIsland():
    return render_template("east/Changi_Bay_Point.html")


@east.route('/east/JapaneseCemeteryPark')
def viewJapaneseCemeteryPark():
    return render_template("east/Japanese_Cemetery_Park.html")

routes/enquiry.py
import shelve

from flask import Blueprint, render_template
from flask import flash, render_template, redirect, url_for, request

from classes.Enquiry import Enquiry
from forms import createEnquiryForm

enquiry = Blueprint('enquiry', __name__)


@enquiry.route('/ContactUs', methods=['GET', 'POST'])
def viewEnquiry():
    form = createEnquiryForm(request.form)

    if request.method == 'POST' and form.validate():
        name = form.name.data
        email = form.email.data
        purpose = form.purpose.data
        query = form.query.data
        this_enquiry = Enquiry(name, email, purpose, query)

        with shelve.open('enquiry', writeback='True') as enquiries:
            enquiries[str(this_enquiry.getId())] = this_enquiry

        flash('Thank you for contacting Explore Singapore. We will get back to you shortly.', category='success')
        return redirect(url_for("enquiry.viewEnquiry"))
    else:
        flash('Unable to create form, please retry again!')
    return render_template("enquiry/viewEnquiry.html", form=form)

routes/north.py
import shelve

from flask import Blueprint, render_template
from flask import flash, render_template, redirect, url_for, request

from classes.Enquiry import Enquiry
from forms import createEnquiryForm

north = Blueprint('north', __name__)

@north.route('/north')
def viewNorth():
    return render_template("north/north.html")

@north.route('/north/KranjiMarshes')
def viewKranjiMarshes():
    return render_template("north/Kranji_Marshes.html")


@north.route('/north/HampsteadWetlandPark')
def viewHampsteadWetlandPark():
    return render_template("north/Hampstead_Wetlands_Park.html")

routes/south.py
import shelve

from flask import Blueprint, render_template
from flask import flash, render_template, redirect, url_for, request

from classes.Enquiry import Enquiry
from forms import createEnquiryForm

south = Blueprint('south', __name__)

@south.route('/south')
def viewSouth():
    return render_template("south/south.html")

@south.route('/south/LazarusIsland')
def viewLazarusIsland():
    return render_template("south/Lazarus_Island.html")


@south.route('/south/BerlayerCreekBoardwalk')
def viewBerlayerCreekBoardwalk():
    return render_template("south/Berlayer_Creek_Boardwalk.html")


@south.route('/south/StJamesPowerStation')
def viewStJamesPowerStation():
    return render_template("south/St_James_Power_Station.html")


@south.route('/south/VintageCameraMuseum')
def viewVintageCameraMuseum():
    return render_template("south/Vintage_Camera_Museum.html")


@south.route('/south/WoodInTheBooks')
def viewWoodInTheBooks():
    return render_template("south/Wood_In_The_Books.html")


@south.route('/south/RotundaLibraryArchive')
def viewRotundaLibraryArchive():
    return render_template("south/Rotunda_Library_Archive.html")

routes/west.py
import shelve

from flask import Blueprint, render_template
from flask import flash, render_template, redirect, url_for, request

from classes.Enquiry import Enquiry
from forms import createEnquiryForm

west = Blueprint('west', __name__)

@west.route('/west')
def viewWest():
    return render_template("west/west.html")

@west.route('/west/JunkiesCorner')
def viewJunkiesCorner():
    return render_template("west/Junkies_Corner.html")


@west.route('/west/MajuForest')
def viewMajuForest():
    return render_template("west/Maju_Forest.html")

templates/base.html
{% import "includes/formHelper.html" as formHelper %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>

    {% block navbar %}
        {% include "includes/navbar.html" %}
    {% endblock%}

    {% block content %}
    {% endblock %}


</body>
{% block footer %}
    {% include "includes/footer.html" %}
{% endblock %}
{% block scripts %}{% endblock %}
</html>

templates/central/Dragon_Playground.html
{% extends 'base.html' %}
{% block title %}Explore Singapore - Dragon Playground{% endblock %}
{% block content %}
<style>


    #containerabout {
        width: 100%;
        height: 90vh;
        background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(https://www.roots.gov.sg/-/media/Roots/Images/landmarks/toa-payoh-trail/Toa-Payoh-Dragon-Playground-Singapore-Heritage-Festival.ashx);
        background-size: cover;
        background-position: center center;
        background-repeat: no-repeat;
        display: flex;
        align-items: center;
        justify-content: center;
        color: #fff;
        font-size: 2vw;
        max-height: 600px;
        margin-bottom: 10px;
    }


</style>
<body>
        <!-- breadcrumbs -->
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="../homepage/index.html">Home</a></li>
                <li class="breadcrumb-item"><a href="../places to visit/places to visit.html">Places to Explore</a></li>
                <li class="breadcrumb-item"><a href="../central/central.html">Central</a></li>
                <li class="breadcrumb-item active" aria-current="page">Dragon Playground</li>
            </ol>
        </nav>

    <!-- Header Image -->
    <div id="containerabout">
        <div class="centered">
            <h2 class="headerabout" id="header">Dragon Playground</h2>
        </div>
    </div>
    <div class="container" id="containerbackground">
        <div class="container" id="container2">
            <div class="row">
                <div class="col-12">
                    <h2 class="header">About Us</h2>
                </div>
                <div class="col-12">
                    <p>
                        One of the early playgrounds designed by the Housing & Development Board, Toa Payoh's Dragon Playground is one of two remaining playgrounds with this dragon design in Singapore. Two smaller playgrounds with dragon designs can also be found in Braddell and MacPherson.                        </p>
                </div>
                <div class="col-12">
                    <h2 class="header">History</h2>
                </div>
                <div class="col-12">
                    <p>
                        In the 1970s, the Housing & Development Board designed a range of playground designs for its public housing estates. The first series was animal themed while the second wave of playgrounds featured objects and concepts easily identifiable with the local culture.<br><br>The Dragon Playground, built in 1979, followed an earlier experiment with a dragon design built in the Toa Payoh Town Park. The earlier dragon had a longer spine, metal head and a circular monkey bar. As feedback came back that the dragon was too long and that the initial metal head was too difficult to faricate, a new design was adopted.<br><br>In 1979, the new dragon design featured a larger head tiled with terrazzo and tiles as well as a body of colourfully-painted steel rings which children could either slide or climb through. The use of terrazzo tiles produced a mosaic aesthetic that remains beloved decades after the dragon playground’s construction.<br><br>This playground is one of two remaining playgrounds in Singapore with this design, the other being located in Ang Mo Kio. The Toa Payoh playground retains its original sand surface and two smaller playgrounds with dragon designs can be found in Braddell and MacPherson.
                    </p>
                    <p>Credits: <a href="https://www.roots.gov.sg/places/places-landing/Places/landmarks/toa-payoh-trail/toa-payoh-dragon-playground">Roots</a></p>
                </div>
            </div>
        </div>
        <div class='container' id="container2">
            <div class="row">
                <div class="col-6">
                    <h2 class="header">Map</h2>
                    <div class="iframe-rwd">
                        <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d705.1163605904803!2d103.85400654972376!3d1.3318272770044728!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da17648d4dcabb%3A0x5c0f4ce489072a82!2sDragon%20Playground%20(Singapore%20Heritage)!5e0!3m2!1sen!2ssg!4v1659791660982!5m2!1sen!2ssg" ></iframe>
                        <br>
                        <small>
                          <a href="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d705.1163605904803!2d103.85400654972376!3d1.3318272770044728!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da17648d4dcabb%3A0x5c0f4ce489072a82!2sDragon%20Playground%20(Singapore%20Heritage)!5e0!3m2!1sen!2ssg!4v1659791660982!5m2!1sen!2ssg"  style="color:#0000FF;text-align:left">View Larger Map</a>
                        </small>
                    </div>
                </div>
                <div class = 'col-6'>
                    <h2 class="header">Operating Hours</h2>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Days</th><th>Timing</th>
                            </tr>
                        </thead>
                        <tbody >
                            <tr>
                                <td>Monday-Sunday</td><td>Open 24 hours</td>
                            </tr>
                        </tbody>
                    </table>
                    <p>*Please note that some venues may be subject to opening hours, please visit their official website to confirm opening hours</p>
                </div>
            </div>
        </div>
    </div>
    <!-- End of .container -->
    <script type="text/javascript">
        var myModal = document.getElementById("myModal");
        var myInput = document.getElementById("myInput");
        myModal.addEventListener("shown.bs.modal", function () {
            myInput.focus();
        });
    </script>
</body>
{% endblock %}

templates/east/Changi_Bay_Point.html
{% extends 'base.html' %}
{% block title %}Explore Singapore - Changi Bay Point{% endblock %}
{% block content %}
<style>
    #containerabout {
        width: 100%;
        height: 90vh;
        background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(../../static/img/east/1.jpg);
        background-size: cover;
        background-position: center center;
        background-repeat: no-repeat;
        display: flex;
        align-items: center;
        justify-content: center;
        color: #fff;
        font-size: 2vw;
        max-height: 600px;
        margin-bottom: 10px;
    }
</style>
<body>

        <!-- breadcrumbs -->
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="../homepage/index.html">Home</a></li>
                <li class="breadcrumb-item"><a href="../places to visit/places to visit.html">Places to Explore</a></li>
                <li class="breadcrumb-item"><a href="../east/east.html">East</a></li>
                <li class="breadcrumb-item active" aria-current="page">Changi Bay Point</li>
            </ol>
        </nav>

    <!-- Header Image -->
    <div id="containerabout">
        <div class="centered">
            <h2 class="headerabout" id="header">Changi Bay Point</h2>
        </div>
    </div>
    <div class="container" id="containerbackground">
        <div class="container" id="container2">
            <div class="row">
                <div class="col-12">
                    <h2 class="header">About Us</h2>
                </div>
                <div class="col-12">
                    <p>
                        Changi Bay Park Connector forms part of the eastern corridor of the Round-Island-Route. At 3.6km long, it connects Changi Beach Park to the East Coastal Park Connector Network.Completed and opened to the public in January 2022, it offers a scenic coastal route for cyclists and hikers who travel from East Coast Park to Changi Beach Park.
                    </p>
                </div>
                <div class="col-12">
                    <h2 class="header">Landmarks</h2>
                </div>
                <div class="col-12">
                    <p>
                        <span id="smallheader">Boardwalk and lookout pavilion at Changi Bay Point</span><br>
                        The boardwalk at Changi Bay Point is connected to a breakwater, bringing visitors closer to the water’s edge. There is also a pavilion with benches near the boardwalk that offers a sweeping vista of the waterfront. Visitors can then rest while appreciating the scenic and tranquil setting of the coast.                            <br>
                        <br>
                        <span id="smallheader">Cycling bridges at Changi Bay Point</span><br>
                        There are two cycling bridges at Changi Bay Point connecting Changi Coast Road and Tanah Merah Coast. They look out over the waterfront, providing visitors with a scenic view of nature as they continue on the Round Island Route.<br><br>The two bridges are around 80m-long, with glass fiber reinforced concrete finish for the decking, a durable and slip resistant material that simulates natural timber, maintaining the area’s rustic character.                            <br>
                    </p>
                    <p>Credits: <a href="https://www.nparks.gov.sg/gardens-parks-and-nature/park-connector-network/changi-bay-pc">NParks</a></p>
                </div>
            </div>
        </div>
        <div class='container' id="container2">
            <div class="row">
                <div class="col-6">
                    <h2 class="header">Map</h2>
                    <div class="iframe-rwd">
                        <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d33807.37266826511!2d104.02176466648974!3d1.3328128518421647!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x512866b77740a45!2sChangi%20Bay%20Point!5e0!3m2!1sen!2ssg!4v1659785379302!5m2!1sen!2ssg" ></iframe>
                        <br>
                        <small>
                          <a href="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d33807.37266826511!2d104.02176466648974!3d1.3328128518421647!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x512866b77740a45!2sChangi%20Bay%20Point!5e0!3m2!1sen!2ssg!4v1659785379302!5m2!1sen!2ssg"  style="color:#0000FF;text-align:left">View Larger Map</a>
                        </small>
                    </div>
                </div>
                <div class = 'col-6'>
                    <h2 class="header">Operating Hours</h2>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Days</th><th>Timing</th>
                            </tr>
                        </thead>
                        <tbody >
                            <tr>
                                <td>Monday-Sunday</td><td>Open 24 hours</td>
                            </tr>
                        </tbody>
                    </table>
                    <p>*Please note that some venues may be subject to opening hours, please visit their official website to confirm opening hours</p>
                </div>
            </div>
        </div>
    </div>

    <!-- End of .container -->
</body>
{% endblock %}

templates/enquiry/viewEnquiry.html
{% extends "base.html" %}
{% block title %}Explore Singapore - Contact Us{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-6">
        <form method = 'post' enctype="multipart/form-data">
            <div class="mb-3">
                {{ formHelper.renderField(form.name) }}
            </div>
            <div class="mb-3">
                {{ formHelper.renderField(form.email) }}
            </div>
            <div class="mb-3">
                {{ formHelper.renderField(form.purpose) }}
            </div>
            <div class="mb-3">
                {{ formHelper.renderField(form.query) }}
            </div>
            <div class="mb-3">
                {{ formHelper.renderField(form.submit) }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/includes/navbar.html
<!--Navbar for website-->
<nav class="navbar navbar-expand-lg navbar-light " style="z-index: 1000000;">
    <a class="navbar-brand" href="../homepage/index.html" style="font-weight: bold;">Explore Singapore</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent" >
        <ul class="navbar-nav mr-auto" id="navbar" >
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('home')  }}"><h5 >Home</h5><span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="../aboutus/aboutus.html"><h5 >About Us</h5></a>
            </li>
            <li class="nav-item dropdown" style="display: inline-block;" >
                <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" data-bs-toggle="dropdown"><h5>Places to visit</h5></a>
                <div class="dropdown-menu dropdown-large">
                    <div class="row g-3">
                        <div class="col-4">
                            <h4 class="title"><a href="../places to visit/places to visit.html">Places to Visit</a></h4>
                        </div>
                    </div>
                    <div class="row g-3">
                        <div class="col-4">
                            <h5 class="title"><a href="../north/north.html">North</a></h5>
                            <ul class="list-unstyled">
                                <li><a href="../north/Hampstead_Wetlands_Park.html">Hampstead Wetlands Park</a></li>
                                <li><a href="../north/Kranji_Marshes.html">Kranji Marshes</a></li>
                            </ul>
                        </div>
                        <!-- end col-3 -->
                        <div class="col-4">
                            <h5 class="title"><a href="{{ url_for('south.viewSouth')}}">South</a></h5>
                            <ul class="list-unstyled">
                                <li><a href="{{ url_for('south.viewStJamesPowerStation')  }}">St James Power Station</a></li>
                                <li><a href="{{ url_for('south.viewRotundaLibraryArchive')  }}">Rotunda Library & Archive</a></li>
                                <li><a href="{{ url_for('south.viewWoodInTheBooks')  }}">Wood in the Books</a></li>
                                <li><a href="{{ url_for('south.viewVintageCameraMuseum')  }}">Vintage Camera Museum</a></li>
                                <li><a href="{{ url_for('south.viewLazarusIsland')  }}">Lazarus Island</a></li>
                                <li><a href="{{ url_for('south.viewBerlayerCreekBoardwalk')  }}">Berlayer Creek Boardwalk</a></li>
                            </ul>
                        </div>
                        <!-- end col-3 -->
                        <div class="col-4">
                            <h5 class="title"><a href="../east/east.html">East</a></h5>
                            <ul class="list-unstyled">
                                <li><a href="../east/Changi_Bay_Point.html">Changi Bay Point</a></li>
                                <li><a href="../east/Japanese_Cemetery_Park.html">Japanese Cemetry Park</a></li>
                            </ul>
                        </div>
                        <!-- end col-3 -->
                    </div>
                    <!-- end row -->
                    <hr style="background-color: white;" />
                    <div class="row g-3">
                        <div class="col-4">
                            <h5 class="title"><a href="../west/west.html">West</a></h5>
                            <ul class="list-unstyled">
                                <li><a href="../west/Junkies_Corner.html">Junkies Corner</a></li>
                                <li><a href="../west/Maju_Forest.html">Maju Forest</a></li>
                            </ul>
                        </div>
                        <!-- end col-3 -->
                        <div class="col-4">
                            <h5 class="title"><a href="../central/central.html">Central</a></h5>
                            <ul class="list-unstyled">
                                <li><a href="../central/Dragon_Playground.html">Dragon Playground </a></li>
                                <li><a href="../central/National_Orchid_Garden.html">National Orchid Garden </a></li>
                            </ul>
                        </div>
                        <!-- end col-3 -->
                    </div>
                    <!-- end row -->
                    <!-- end row -->
                </div>
                <!-- dropdown-large.// -->
            </li>
            <li class="nav-item" >
                <a class="nav-link d-flex align-items-center" href="../blog/blog home.html"><h5>Blog</h5></a>
            </li>
        </ul>
    </div>
</nav>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function () {
        /////// Prevent closing from click inside dropdown
        document.querySelectorAll(".dropdown-menu").forEach(function (element) {
            element.addEventListener("click", function (e) {
                e.stopPropagation();
            });
        });
    });
</script>

templates/south/Vintage_Camera_Museum.html
{% extends 'base.html' %}
{% block title %}Explore Singapore - Vintage Camera Museum {% endblock %}
{% block content %}
<style>
    #containerabout {
        width: 100%;
        height: 90vh;
        background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(https://www.vintagecamerasmuseumsg.com/admin/views/gallery/211117102217.jpg);
        background-size: cover;
        background-position: center center;
        background-repeat: no-repeat;
        display: flex;
        align-items: center;
        justify-content: center;
        color: #fff;
        font-size: 2vw;
        max-height: 600px;
        margin-bottom: 10px;
    }
</style>
<body>

        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('home')  }}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{ url_for('south.viewSouth') }}"></a>Places to Explore</li>
                <li class="breadcrumb-item"><a href="{{ url_for('south.viewSouth') }}"></a>South</li>
                <li class="breadcrumb-item active"><a href="{{ url_for('south.viewVintageCameraMuseum') }}"></a>Vintage Camera Museum</li>
            </ol>
        </nav>
    
    <!-- Header Image -->
    <div id="containerabout">
        <div class="centered">
            <h2 class="headerabout" id="header">Vintage Camera Museum</h2>
        </div>
    </div>
    <div class="container" id="containerbackground">
        <div class="container" id="container2">
            <div class="row">
                <div class="col-12">
                    <h2 class="header">About Us</h2>
                </div>
                <div class="col-12">
                    <p>
                        The Vintage Camera's Museum, itself is set in the form of a camera, and the entry is shaped like a lens. There are around 1000 cameras in display right from replicas of the world's biggest camera - the mammoth camera till the latest technological gadget, a 11 gram camera. Some of the other unique cameras which can be viewed in the museum are a walking stick camera, spy cameras, pigeon cameras, 3D camera and pistol cameras to name a few. Besides, the museum also has on display, rare collection of photographs featuring interesting facets about photography including an authentic replica of the first ever photograph taken. Visit us to witness the unique experience to learn about the transformation and the untold story of cameras.
                    </p>
                </div>


                <p>Credits: <a href="https://www.vintagecamerasmuseumsg.com/" target="_blank" rel="noopener noreferrer">Vintage Camera Museum</a></p>
            </div>
        </div>
        <div class='container' id="container2">
            <div class="row">
                <div class="col-6">
                    <h2 class="header">Map</h2>
                    <div class="iframe-rwd">
                        <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15955.143356770961!2d103.8590172!3d1.3035014!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5ab694c088592038!2sVintage%20Camera%20Museum!5e0!3m2!1sen!2ssg!4v1659267867761!5m2!1sen!2ssg" ></iframe>
                        <br>
                        <small>
                          <a href="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15955.143356770961!2d103.8590172!3d1.3035014!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5ab694c088592038!2sVintage%20Camera%20Museum!5e0!3m2!1sen!2ssg!4v1659267867761!5m2!1sen!2ssg"  style="color:#0000FF;text-align:left">View Larger Map</a>
                        </small>
                    </div>
                </div>
                <div class = 'col-6'>
                    <h2 class="header">Operating Hours</h2>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Days</th><th>Timing</th>
                            </tr>
                        </thead>
                        <tbody >
                            <tr>
                                <td>Monday-Sunday</td><td>10:30am – 7:30pm </td>
                            </tr>
                        </tbody>
                    </table>
                    <p>*Please note that some venues may be subject to opening hours, please visit their official website to confirm opening hours</p>
                    <h2 class="header">Contact Details</h2>
                    <table class="table table-hover">
                        <tbody >
                            <tr>
                                <td>Phone Number:</td><td>+65 6291 2278</td>
                            </tr>
                            <tr>
                                <td>Email:</td><td>ram@wemuseums.com</td>
                            </tr>
                        </tbody>
                    </table>
                    <h2 class="header">Visit Official Site</h2>
                    <table class="table table-hover">
                        <tbody >
                            <tr>
                                <td><a href="https://www.vintagecamerasmuseumsg.com/" target="_blank" rel="noopener noreferrer">Vintage Camera Museum</a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End of .container -->
    <script type="text/javascript">
        var myModal = document.getElementById("myModal");
        var myInput = document.getElementById("myInput");
        myModal.addEventListener("shown.bs.modal", function () {
            myInput.focus();
        });
    </script>
</body>
{% endblock %}